version: 2
updates:
# Updates for Github Actions used in the repo
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
# Updates for Gradle dependencies used in the app      
    - package-ecosystem: gradle
      directory: "/"
      schedule:
        interval: "weekly"
      open-pull-requests-limit: 10
      ignore:
        - dependency-name: com.google.firebase:firebase-ml-natural-language
          versions: "> 19.0.0"
        - dependency-name: com.google.firebase:firebase-ml-natural-language-smart-reply-model
          versions: "> 19.0.0"
        - dependency-name: com.google.firebase:firebase-ml-natural-language-language-id-model
          versions: "> 19.0.0"
        - dependency-name: com.google.firebase:firebase-ml-natural-language-translate-model  
          versions: "> 19.0.0"
